title: Home Cooked Router
email: steve@work.renlabs.com
description: "Setting up a SBC as the home router"
baseurl: "home-cooked-router" # the subpath of your site, e.g. /blog
url: "https://swork.github.io"
github_username:  swork

# Build settings
theme: minima
plugins:
  - jekyll-feed
